-- 1 (175. Combine Two Tables)

SELECT P.FIRSTNAME, P.LASTNAME, A.CITY, A.STATE FROM PERSON AS P LEFT JOIN ADDRESS AS A ON P.PERSONID = A.PERSONID

--X (PALLINDROME)

SELECT * 
FROM your_table 
WHERE LOWER(column_name) = REVERSE(LOWER(column_name));