-- 1 (175. Combine Two Tables)

SELECT P.FIRSTNAME, P.LASTNAME, A.CITY, A.STATE FROM PERSON AS P LEFT JOIN ADDRESS AS A ON P.PERSONID = A.PERSONID

--2 (181. Employees Earning More Than Their Managers)

SELECT 
NAME AS EMPLOYEE 
FROM EMPLOYEE AS T3 
LEFT JOIN 
(SELECT 
T1.MANAGERID AS MID, T2.SALARY AS MSALARY 
FROM EMPLOYEE AS T1 
LEFT JOIN 
EMPLOYEE AS T2 
ON T1.MANAGERID = T2.ID
) AS T4 
ON T3.MANAGERID = T4.MID  
WHERE T3.SALARY > T4.MSALARY

--&

SELECT T1.NAME AS EMPLOYEE FROM EMPLOYEE AS T1 LEFT JOIN EMPLOYEE AS T2 ON T1.MANAGERID = T2.ID WHERE T1.SALARY > T2.SALARY


--3 (182. Duplicate Emails)

SELECT DISTINCT(T1.EMAIL) AS Email FROM PERSON AS T1 LEFT JOIN (
     SELECT EMAIL, COUNT(EMAIL) AS E FROM PERSON GROUP BY EMAIL
) AS T2 ON T1.EMAIL = T2.EMAIL  WHERE T2.E > 1
 
 --& 

SELECT EMAIL
FROM PERSON
GROUP BY EMAIL
HAVING COUNT(*) > 1;


--X (PALLINDROME)

SELECT * 
FROM your_table 
WHERE LOWER(column_name) = REVERSE(LOWER(column_name));

--X (Duplicate Emails)

SELECT Email, COUNT(Email)
FROM Users
GROUP BY Email
HAVING COUNT(Email) > 1;
