--1

SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 65000;

--2

SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING ((AVG(SALARY) > 65000) AND (AVG(SALARY) < 80000));


--3

SELECT 
    COUNT(CASE WHEN marks >= 90 THEN 1 END) AS students_90_plus,
    COUNT(CASE WHEN marks < 90 THEN 1 END) AS students_90_minus
FROM students;


--4

SELECT MAX(salary) AS second_highest_salary 
FROM employees 
WHERE salary < (SELECT MAX(salary) FROM employees);