--1

SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 65000;

--2

SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING ((AVG(SALARY) > 65000) AND (AVG(SALARY) < 80000));
